### ISSUE TITLE
[QUESTION] How to trigger /parse for a list of URLs?

### ISSUE THREAD

**Issue by johnghill** [sawhney17/logseq-twitter-extractor#2]
Thank you for this plugin. I would like to render a list of twitter bookmarks without having to enter each of their blocks to trigger a `/Parse Twitter URL` slash command. In my tests, adding a list of URLs in the form `[tab] - [URL] /Parse Twitter URL` to the source `.md` file does not render anything until I enter each block. Obviously, for a large number of bookmarks this is quite cumbersome. Is there an alternative?

My template:
```
{
  "InsertionTemplateForBlock1": "{Name} (@{UserName}) tweeted on {Date}:",
  "InsertionTemplateForBlock2": "{TWEET} {{tweet {URL}}}",
  "disabled": false
}
```

**Comment by sawhney17** [comment]
It's not currently possible. How would the option to select multiple blocks work for you? I think that's what you want right? I will see if I can add it

**Comment by johnghill** [comment]
> How would the option to select multiple blocks work for you?

I think that could work... although there's probably an upper limit on the number of URLs it can pass at once?

**Comment by sawhney17** [comment]
Latest release should fix this

**Comment by johnghill** [comment]
Works perfectly @sawhney17 thank you!
